### PR TITLE
changed login prompt from username to email

### PR DESCRIPTION
**Pull request by jwpeterkim**
## Description

What does the PR do?
--> Instead of "username", the login prompt now asks for "email".

## Background Information
It was not straightforward to ask for a username when it really is an email address.

## Screenshots
Screen Shot 2021-01-25 at 16 02 13

## Checklist:
- [v] Screenshots attached (if dealing with UI)
- [ ] Unit Tests (if applicable)

## Testing Steps for reviewer:
- Step 1
click on the login button
- Step 2
see the Sign in page with the placeholder title "email".

### CODE REVIEW

**Review by kidatsy — COMMENTED** [review]
That was easy, haha! Are we sure there are no other instances of `Username`? Have you checked the registration flow as well?

**Comment by jwpeterkim** [comment]
> That was easy, haha! Are we sure there are no other instances of `Username`? Have you checked the registration flow as well?

That's what I thought! I did try to find other instances but couldn't. But let me just double check once more and I'll let you know!

**Review by kidatsy — APPROVED** [review]
Alright, cool. I guess if we find more later, we can always pull another PR 👍  Approved!

**Comment by jwpeterkim** [comment]
> Alright, cool. I guess if we find more later, we can always pull another PR 👍 Approved!

Sorry I forgot to get back to you. I checked again and didn't find other instances and it should be fine!

**Pull request merged**
